[package]
name = "day12"
version = "0.1.0"
authors = ["John Hungerford <jhungerford@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
itertools = "0.10.1"
num = "0.4.0"
